### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by codyjoliphant** [yasglobal/custom-permalinks#5] opened 2018-01-22 21:14 UTC
It appears that Pagination on Child Pages is broken. For example, if I have a child page with the custom permalink **example.com/custom/**, the link **example.com/custom/page/2/** will not work.

This is not an issue in version 1.2.8, fyi.

**Comment by samiahmedsiddiqui** [comment] 2018-01-23 21:37
@codyjoliphant Issue is fixed in the v1.2.11. Please verify the issue at your end.

Thanks

**Comment by codyjoliphant** [comment] 2018-01-23 21:42
@samiahmedsiddiqui The issue seems to be resolved in v1.2.11. Thanks!

**Comment by samiahmedsiddiqui** [comment] 2018-01-23 21:43
@codyjoliphant Thanks for you confirmation. Have a good day..!

**Closed by samiahmedsiddiqui** 2018-01-23 21:43 UTC
Labels: bug, fixed

**Comment by samiahmedsiddiqui** [comment] 2018-01-24 20:20
@codyjoliphant Kindly Check the v1.2.12. I have just released the version and one of the customer confirmed that the issue is fixed for him.

You can check at your end.

**Comment by codyjoliphant** [comment] 2018-01-24 20:24
@samiahmedsiddiqui Looks like it's all good now. Thanks again.

**Comment by samiahmedsiddiqui** [comment] 2018-01-24 20:26
@codyjoliphant Thanks for the quick response and providing your feedback. 💯 

Have a good day 😄

**Comment by sdwkn** [comment] 2018-03-09 07:48
It's still broken.

**Comment by samiahmedsiddiqui** [comment] 2018-03-09 10:46
@sdwkn What's the issue you are facing? Can you please define?

Also, please mention the version of your WordPress and the plugin.
